model:
  arch: blip2_emac
  model_type: vicuna7b
  
  load_basemodel: True
  load_finetuned: False
  load_pretrained: True
  
  base_model: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/InstructBLIP/instruct_blip_vicuna7b_trimmed.pth"
  # ref_pretrained: "/srv/scratch/z5428797/EMAC-Embodied-Multimodal-Agent-for-Collaborative-Planning-with-VLM-LLM/output/dagger_server_human_desc/with_bc_dpo-True-tc-False-<TIMESTAMP>/emma_checkpoint_11.pth"
  # pretrained: "/srv/scratch/z5428797/EMAC-Embodied-Multimodal-Agent-for-Collaborative-Planning-with-VLM-LLM/output/dagger_server_human_desc/with_bc_dpo-True-tc-False-<TIMESTAMP>/emma_checkpoint_11.pth"
  # Update <TIMESTAMP> with the actual run folder name after training.

  # emac
  low_memory: True

  # vit encoder
  freeze_vit: True
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"

  # Q-Former
  num_query_token: 32
  qformer_text_input: False
  adaptor_tuning: False
  freeze_qformer: True
  freeze_proj_layer: False

  # path to Vicuna checkpoint
  llm_model: "/srv/scratch/z5428797/models/vicuna-7b-v1.1"
  max_txt_len: 1024
  max_output_txt_len: 128

  # dpo's configs
  avg_log_probs: True
  mix_ratio: 0.5

  # misc
  apply_lemmatizer: False

preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_alfworld"
          prompt: ""
          max_words: 1024
        eval:
          name: "blip_alfworld"
          prompt: ""
          max_words: 1024
